#!/bin/bash

# check for *.monster 
#monsters are gurading there is no way past them. Kill them all and re-enter.

if [ -f  "*.monster" ]; then
    echo "monsters are gurading there is no way past them. Kill them all and re-enter."
    exit
fi

if ! grep  --quiet --only-matching crystal <<< $I; then
 echo "go back and collect all the items from chapel & vault and come back to this tunnel"
 exit
fi

if ! grep  --quiet --only-matching rags <<< $I; then
 echo "go back and collect all the items from chapel & vault and come back to this tunnel"
 exit
fi

if ! grep  --quiet --only-matching goblet <<< $I; then
 echo "go back and collect all the items from chapel & vault and come back to this tunnel"
 exit
fi


echo "Found a new and easier sea route to the east"

echo "Well done Traveller. You have reached the end of this adventure . Best of luck for your future POSIX journies. So long"
echo ""
echo "Summary:"

echo "Inventory: $I"
echo "HP: $HP"